### ISSUE TITLE
three.js has this kind of adapter mechanism ..

### ISSUE THREAD

**Issue by brownman** [sinisterchipmunk/webgl-compat#1]
please correct me if i'm wrong

**Comment by sinisterchipmunk** [comment]
Three.js has a specialized renderer that adapts Three.js scenes to a Canvas2D. It is by no means a WebGL context, and makes no attempt to pretend to be one. While this works fine for Three.js, it is neither portable nor compatible with apps designed to use purely the official WebGL spec -- let alone being able to use it with other frameworks.

This project aims to provide a totally standards-compliant context so that a user may simply drop the webgl-compat library into their app, change the context creation call to go through this library first, and have everything they'e written for WebGL "Just Work". It's totally different from the Three.js renderer, and it theoretically would be compatible with any framework out there as long as you can control how the WebGL context is created.
